spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gitrank?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    redis:
      host: redis
      port: 6379
